[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mijn_project"
version = "0.1.0"
description = "Een professioneel opgezet Python-project"
authors = [
  {name = "Jouw Naam", email = "jouw@email.com"}
]
dependencies = []